collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.5297872
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#0F1120'
    - '#95A9F0'
    - '#6D75A3'
    - '#E7C39F'
  rhythmicContrast: 0
typography_spectrum: 0.8680159
layout_spectrum: 0.2042553
name: Vijay Travel Blog
