layout_spectrum: 0.7523099
typography_spectrum: 0.8680159
color:
  saturation: 0.5816217
  lightness: 0.5114679
  brandStrength: 0.6540754
  rhythmicContrast: 0.9765401
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Vijay Travel Blog
